public class processrecordhelper {

    
    public void processrecord(account acc)
    {
        system.debug('line 6 process!!!!');
     /*   http h = new http();
        httprequest req = new httprequest();
        req.setEndpoint('https://dummyjson.com/posts/1');
        req.setMethod('GET');
        httpresponse res = h.send(req);*/
        //system.debug(res.getBody());
        system.debug('line 12');       
    }
}