public class WireExecution {
    
    
    @auraenabled(cacheable = true)
    public static string wirecheck(string varr)
    {  system.debug('line 6'+varr);
      /*  for(integer i =0;i <10000000;i++)
        {

        }*/
        return ' wire check33';
    }
     @auraenabled(cacheable = true)
    public static string wirecheck2(string varr)
    {  system.debug('line 6'+varr);
      /*  for(integer i =0;i <10000000;i++)
        {

        }*/
        return ' wire check33';
    }

}